language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  fast_finish: true

services:
  - memcached

before_script:
  - echo 'extension = "memcached.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - ./scripts/travis
  - composer init --no-interaction --stability=dev
  - composer require "photon/session-memcached:dev-master"
  - cp vendor/photon/session-memcached/phpunit.xml .
  
script: phpunit -c phpunit.xml

